export const FETCHING_CART = 'FETCHING_CART';
export const FETCHING_CART_PRODUCTS_SUCCESS = 'FETCHING_CART_PRODUCTS_SUCCESS';
export const FETCHING_CART_PRODUCTS_FAILURE = 'FETCHING_CART_PRODUCTS_FAILURE';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';
