export const FETCHING_FILTERS = 'FETCHING_CART';
export const FETCHING_FILTERS_SUCCESS = 'FETCHING_FILTERS_SUCCESS';
export const FETCHING_FILTERS_FAILURE = 'FETCHING_FILTERS_FAILURE';

export const FILTER_TYPE_CATEGORY = 'FILTER_TYPE_CATEGORY';
export const FILTER_TYPE_PRICE = 'FILTER_TYPE_PRICE';
export const FILTER_TYPE_SIZE = 'FILTER_TYPE_SIZE';
